version: "3.9"
services:
  clock:
    build: .
    command: python clock.py
    volumes:
      - .:/app
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - VACCINE_CHECK_INTERVAL=60
      - ENABLE_HYVEE=true
      - ENABLE_WALGREENS=true
      - ENABLE_CVS=true
      - RADIUS=20
      - LATITUDE=39.1018061
      - LONGITUDE=-94.5812623
      - ZIP_CODE=64106
      - SLACK_TAG_CHANNEL=false
    env_file:
      - .env
  redis:
    image: "redis:alpine"
